---
version: "2.1"
services:
  blog:
    image: nicholaswilde/blog:latest
    container_name: blog
    environment:
      TZ: America/Los_Angeles
      BLOG_TITLE: Blog
      BLOG_NAME: Max Musermann
      BLOG_NICK: username
      BLOG_PASS: password
      BLOG_LANG: en
    ports:
      - 80:80
    restart: unless-stopped
    volumes:
      - data:/var/www/html/data
volumes:
  data:
